---
- name: Initialize MariaDB
  command: mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
  args:
    creates: /var/lib/mysql/mysql

- name: Enable and start services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - lightdm
    - mariadb
    - nginx

- name: Enable and start VirtualBox guest service
  ansible.builtin.systemd:
    name: vboxservice
    enabled: true
    state: started
  when: ansible_virtualization_type == "virtualbox"
