---
- name: Install dev and desktop packages
  community.general.pacman:
    name:
      - bat
      - bind
      - btop
      - composer
      - direnv
      - eza
      - dnsmasq
      - fd
      - feh
      - fish
      - fzf
      - github-cli
      - i3-wm
      - i3status
      - i3lock
      - lightdm
      - lightdm-gtk-greeter
      - mariadb
      - neovim
      - nginx
      - nodejs
      - npm
      - php
      - php-fpm
      - php-gd
      - php-pgsql
      - php-sqlite
      - pipewire
      - pipewire-pulse
      - ripgrep
      - starship
      - stow
      - thefuck
      - tmux
      - virtualbox-guest-utils
      - viu
      - xclip
      - zoxide
    state: present
